import { DEFAULT_LOCALE } from './index';

const navigation: Record<string, string> = { Main: '主要功能', Workspace: '工作區', Dashboard: '儀表板', Tasks: '任務', Projects: '專案', Reports: '報告', Sessions: '工作階段', Journal: '日誌', 'Second Brain': '第二大腦', Stats: '統計', Tools: '工具', 'Audit Log': '稽核記錄', 'Agent Types': 'Agent 類型', 'Content Engine': '內容中心', Voice: '語音', Images: '圖片', 'On My Mind': '待處理', Agents: 'Agent' };
const ui: Record<string, string> = {
  '💡 Ideas / Plans': '💡 構思／計劃', '📋 To Do': '📋 待辦', '⚡ In Progress': '⚡ 執行中', '🤔 Stuck / Review': '🤔 受阻／審核', '✅ Completed': '✅ 已完成', '📦 Archived': '📦 已封存',
  'Task title:': '任務標題：', 'Are you sure you want to delete this task?': '確定要刪除此任務嗎？', 'No completed tasks to archive': '沒有可封存的已完成任務', 'Archive completed task(s)?': '要封存已完成的任務嗎？', 'Failed to spawn task': '無法啟動任務', 'Failed to spawn:': '啟動失敗：', 'Hide Archived': '隱藏已封存', 'Show Archived': '顯示已封存', 'Archive Completed': '封存已完成任務', 'New Task': '新增任務', 'Search & Filter': '搜尋及篩選', 'thing': '項任務', 'things': '項任務', 'in view': '項顯示中',
  'Create New Project': '建立新專案',  'Cancel': '取消', 'Retry': '重試', 'Status': '狀態', 'Loading...': '載入中...', 'Refresh': '重新整理', 'Close': '關閉', 'Description': '描述', 'Download': '下載', 'Global': '全域', 'Tags': '標籤', 'Context': '上下文', 'Type': '類型', 'Updated': '已更新', 'Delete': '刪除', 'Edit': '編輯', 'Add': '新增', 'Save': '儲存', 'Priority': '優先級', 'Project': '專案', 'Blocked Reason': '受阻原因', 'Why is this stuck?': '受阻原因是什麼？', 'Notes': '備註', 'Clear search': '清除搜尋', 'Filters': '篩選條件', 'Back to Journal': '返回日誌', 'Back to Reports': '返回報告', 'Loading messages...': '正在載入訊息…', 'Loading tool calls...': '正在載入工具呼叫…', 'Used': '已使用', 'Input tokens': '輸入 Token', 'Output tokens': '輸出 Token', 'Total tokens': 'Token 總數', 'Started:': '開始時間：', 'Active Agents': '執行中的 Agent', 'Session:': '工作階段：', 'Execution systems': '執行系統', 'Status unavailable': '狀態暫不可用', 'Fallbacks': '備援模型', 'Notifications': '通知', 'Logout': '登出', 'Loading files...': '正在載入檔案…', 'View All Tasks': '查看所有任務', 'Status History': '狀態歷程', 'Try again': '再試一次', 'Copy to clipboard': '複製到剪貼簿', 'Completed': '已完成', 'Back': '返回', 'Create': '建立', 'Overview': '總覽', 'Reports': '報告', 'Project Resources': '專案資源', 'No resources configured': '尚未設定資源', 'Create Task': '建立任務', 'Loading tasks...': '正在載入任務…', 'Search tools...': '搜尋工具…', 'Link title': '連結標題', 'No Category': '未分類', 'Copy': '複製', 'task': '任務', 'URL': '網址', 'No projects found': '找不到專案', 'Clear all filters': '清除所有篩選', 'Send message (Enter)': '傳送訊息（Enter）', 'Move up': '上移', 'Move down': '下移', 'Success Criteria': '成功準則', 'Task Resources': '任務資源', 'Summary': '摘要', 'Category': '類別', 'Usage Instructions': '使用說明', 'Created': '建立時間', 'Pipeline': '流程', 'Stop agent': '停止 Agent', 'Last Activity': '最近活動', 'Custom persona': '自訂角色', 'Total Tokens': 'Token 總數', 'Page': '頁面', 'Generating...': '正在產生…', 'Previous entry': '上一篇', 'Next entry': '下一篇', 'Clear filters': '清除篩選', 'Cost': '費用', 'Discord': 'Discord',
  'Dashboard': '儀表板', 'Ideas / Plans': '構思／計劃', 'To Do': '待辦', 'In Progress': '執行中', 'Stuck / Review': '受阻／審核', 'Archived': '已封存', 'Urgent': '緊急', 'High': '高', 'Normal': '一般', 'Low': '低', 'Someday': '有空時處理',
  'Project Name *': '專案名稱 *', 'What is this project about?': '專案簡介', 'Paused': '已暫停', 'Create Project': '建立專案', 'New Folder': '新增資料夾', 'Folder name': '資料夾名稱', 'browse': '瀏覽', 'No files found': '找不到檔案', 'Folder': '資料夾', 'Preview': '預覽', 'Empty directory': '資料夾是空的', 'Source files are read-only': '來源檔案為唯讀', 'Details': '詳細資料', 'Resources': '資源', 'Files': '檔案', 'Tools': '工具', 'Total Tasks': '任務總數', 'Overall Progress': '整體進度', 'Task Breakdown': '任務分佈', 'Configure': '設定', 'Project Tasks': '專案任務', 'Task title': '任務標題', 'Description (optional)': '描述（選填）', 'Medium': '中', 'Critical': '緊急', 'No tasks found for this project': '此專案尚無任務', 'Session History': '工作階段記錄', 'No sessions found for this project': '此專案尚無工作階段', 'Project Tools': '專案工具', 'Link Tool': '連結工具', 'No tools linked': '尚未連結工具', 'Global Tools': '全域工具', 'Linked Tools': '已連結工具', 'Override': '覆寫設定', 'Save Override': '儲存覆寫設定', 'Project Reports': '專案報告', 'Add Link': '新增連結', 'No links added yet': '尚未新增連結', 'External URL': '外部網址', 'Git Repository': 'Git 儲存庫', 'Document/File': '文件／檔案', 'API Endpoint': 'API 端點', 'Cross-project': '跨專案', 'Repositories': '儲存庫', 'Environments': '環境', 'Paths': '路徑', 'Notebooks': '筆記本', 'Testing': '測試', 'Deployment': '部署',
  'Create New Task': '建立新任務', 'What needs to be done?': '需要完成什麼？', 'Description (Markdown)': '描述（Markdown）', 'No project': '未指定專案', 'Edit Task': '編輯任務', 'Agent Instructions (Markdown)': 'Agent 指示（Markdown）', 'Thinking Level': '思考程度', 'Save Changes': '儲存變更', 'Search tasks by title or description...': '搜尋任務標題或描述…', 'Search tags...': '搜尋標籤…', 'No tags found': '找不到標籤', 'Confirm?': '確認？', 'Interactive': '互動模式', 'Restore to Completed': '還原為已完成', 'Move task': '移動任務', 'Task details': '任務詳細資料', 'Task title...': '任務標題…', 'Save changes': '儲存變更', 'Priority:': '優先級：', 'ID:': 'ID：', 'Project:': '專案：', 'Tags:': '標籤：', 'Default': '預設', 'Mode:': '模式：', 'Access:': '存取權限：', 'None': '無', 'Active Agent': '執行中的 Agent', 'Auto-start': '自動啟動', 'Auto-created': '自動建立', 'Needs Review': '需要審核', 'No instructions': '沒有指示', 'No notes': '沒有備註', 'Reviewer Settings': '審核設定', 'Retry Budget': '重試上限', 'Review State': '審核狀態', 'Attempts': '嘗試次數', 'Dependencies': '相依任務', 'Timeline': '時間軸', 'Changed Files': '變更檔案', 'Task Timeline': '任務時間軸', 'Delete Task': '刪除任務',
  'Delete tool': '刪除工具', 'Tool name': '工具名稱', 'Global Tool': '全域工具', 'Config (JSON)': '設定（JSON）', 'Version': '版本', 'Connecting...': '正在連線…', 'No recent session activity': '最近沒有工作階段活動', 'Session Archive': '工作階段封存', 'No archived sessions found': '找不到封存的工作階段', 'Duration': '持續時間', 'Modified': '修改時間', 'Search personas...': '搜尋角色…', 'All categories': '所有類別', 'No agent types found': '找不到 Agent 類型', 'Sync from repo': '從儲存庫同步', 'Audit Dashboard': '稽核儀表板', 'Export': '匯出', 'Total Events': '事件總數', 'Success Rate': '成功率', 'Estimated Cost': '預估費用', 'Detailed Breakdown': '詳細明細', 'API Calls': 'API 呼叫次數', 'Input Tokens': '輸入 Token', 'Output Tokens': '輸出 Token', 'All Types': '所有類型', 'Tool Results': '工具結果', 'Model Changes': '模型變更', 'Loading events...': '正在載入事件…', 'No events found for the selected filters.': '所選篩選條件沒有事件。', 'Command:': '指令：', 'Result:': '結果：', 'Metadata:': '中繼資料：', 'Next →': '下一頁 →',
  'Generated': '已產生', 'Screenshots': '截圖', 'Sort:': '排序：', 'Newest First': '最新優先', 'Oldest First': '最舊優先', 'Journal': '日誌', 'Logs': '記錄', 'Mindscape': '心境音景', 'Journal view': '日誌檢視', 'Grid view': '格狀檢視', 'Timeline view': '時間軸檢視', 'No entries yet': '尚無日誌', 'Newer': '較新', 'Older': '較舊', 'Entry not found': '找不到日誌項目', 'Password': '密碼', 'Authenticating...': '正在驗證…', 'Login': '登入', 'Sort by:': '排序方式：', 'Name': '名稱', 'Progress': '進度', 'Create Your First Project': '建立第一個專案', 'Download as Markdown': '下載為 Markdown', 'Edit report': '編輯報告', 'Edit Report': '編輯報告', 'Title': '標題', 'Report title': '報告標題', 'Short summary...': '簡短摘要…', 'Pin this report': '置頂此報告', 'Search reports...': '搜尋報告…', 'All Projects': '所有專案', 'All scopes': '所有範圍', 'Collection': '集合', 'Ingestion pipelines': '匯入流程', 'Last run': '最近執行', 'Items': '項目', 'All harnesses': '所有執行環境', 'All kinds': '所有類型', 'All models': '所有模型', 'All channels': '所有頻道', 'From date': '開始日期', 'To date': '結束日期', 'Transcript unavailable': '逐字稿不可用', 'Live': '即時', 'Refresh sessions': '重新整理工作階段', 'Select a session from the sidebar': '請從側邊欄選擇工作階段', 'More': '更多', 'Last activity:': '最近活動：', 'Persona:': '角色：', 'Parent:': '上層項目：', 'Reason:': '原因：', 'Input:': '輸入：', 'Output:': '輸出：', 'Thinking:': '思考：', 'Total:': '總計：', 'Runtime': '執行環境', 'Transcript': '逐字稿', 'Elapsed': '經過時間', 'Window': '上下文視窗', 'Messages': '訊息', 'Tool calls': '工具呼叫', 'Channel': '頻道', 'Session key': '工作階段金鑰', 'Session ID': '工作階段 ID', 'Depth': '深度', 'Delivery': '傳送方式', 'Destination': '目的地', 'Copy raw text': '複製原始文字', 'Copied': '已複製', 'Stats & Analytics': '統計與分析', 'Search': '搜尋', 'Tools Registry': '工具清單', 'New Tool': '新增工具', 'All Categories': '所有類別', 'All': '全部', 'No tools found': '找不到工具', 'Voice Chat': '語音聊天', 'End': '結束', 'Toggle speaker': '切換喇叭', 'Volume': '音量'
};
const uiTaskExtra: Record<string, string> = {
  'Dashboard version': '控制台版本', 'Password': '密碼', 'Login': '登入', 'Authenticating...': '正在驗證…', 'Good morning': '早晨好', 'Good afternoon': '下午好', 'Good evening': '晚上好', 'Your personal workspace & command center': '你的個人工作空間與指揮中心', '🔄 Currently Working On': '🔄 正在處理', 'Currently Working On': '正在處理', 'All caught up!': '目前已全部跟進！', 'Nothing in progress right now': '目前沒有進行中的工作', 'View All Projects': '查看所有專案', 'Loading projects...': '正在載入專案…', 'Search projects...': '搜尋專案…', 'Status:': '狀態：', 'Secret:': '私密：', '🔒 Show Secret': '🔒 顯示私密專案', 'Try adjusting your search or filters': '請調整搜尋字詞或篩選條件', 'reports': '份報告', 'Loading reports...': '正在載入報告…', 'No reports match your filters': '沒有報告符合目前篩選條件', 'No reports yet': '目前沒有報告', 'View project:': '查看專案', 'Load More': '載入更多',
  'Definition of Done': '完成定義', 'Constraints': '限制條件', 'Status': '狀態', 'Priority': '優先級', 'Title *': '標題 *', 'What needs to be done?': '需要完成什麼？', 'Description (Markdown)': '描述（Markdown）', 'Rich description with markdown support...': '可使用 Markdown 的詳細描述…', '🧠 On My Mind': '🧠 待處理', 'On My Mind': '待處理', 'things in view': '項任務顯示中', 'Archive completed task(s)?': '要封存已完成的任務嗎？', 'No completed tasks to archive': '沒有可封存的已完成任務', 'Are you sure you want to delete this task?': '確定要刪除此任務嗎？', 'Failed to spawn task': '無法啟動任務', 'Hide Archived': '隱藏已封存', 'Show Archived': '顯示已封存', 'Search & Filter': '搜尋及篩選', 'Archive Completed': '封存已完成任務', 'New Task': '新增任務', 'Task title:': '任務標題：', 'Ideas': '構思', 'Todo': '待辦', 'Stuck': '受阻', 'things to explore': '項待探索事項', 'ready to start': '準備開始', 'actively working': '正在處理', 'needs attention': '需要跟進', 'recent': '最近', 'all time': '全部期間', 'filed away': '已整理封存', 'Loading dashboard': '正在載入儀表板', 'Loading dashboard...': '正在載入儀表板…', 'Failed to load dashboard data.': '無法載入儀表板資料。',
  'View All Tasks': '查看所有任務', '📁 Active Projects': '📁 進行中的專案', 'tasks': '項任務', 'stuck': '項受阻',
  'active': '進行中', 'paused': '已暫停', 'completed': '已完成', 'archived': '已封存',
  '💡 Ideas / Plans': '💡 構思／計劃', '📋 To Do': '📋 待辦', '⚡ In Progress': '⚡ 執行中', '🤔 Stuck / Review': '🤔 受阻／審核', '✅ Completed': '✅ 已完成', '📦 Archived': '📦 已封存',
  '🔴 Urgent': '🔴 緊急', '🟠 High': '🟠 高', '🔵 Normal': '🔵 一般', '⚪ Low': '⚪ 低', '🟣 Someday': '🟣 有空時處理',
  'Tags (comma-separated)': '標籤（逗號分隔）', 'Execution Profile': '執行設定', 'Run Mode': '執行模式', 'Harness': '執行器', 'Access Profile': '存取設定', 'Planning Mode': '規劃模式', 'Extra Required Capabilities': '額外所需能力', 'Extra required capabilities': '額外所需能力', 'Included by the selected access profile': '已包含於所選存取設定', 'Request this capability in addition to the access profile': '除存取設定外另外要求此能力', '🔓 Allow spawn-time overrides': '🔓 允許啟動時覆寫設定', 'Let the orchestrator override mode, access profile, model, and extra capabilities when spawning.': '啟動時允許協調器覆寫模式、存取設定、模型及額外能力。', 'AI Model': 'AI 模型', 'Agent Persona *': 'Agent 角色 *', '— Select agent persona —': '— 選擇 Agent 角色 —', '⚡ Auto-pickup enabled': '⚡ 已啟用自動領取', 'Auto-pickup disabled': '已停用自動領取', 'Bot can pick this up during heartbeats': 'Agent 可在 heartbeat 時領取此任務', 'Bot will NOT pick this up on its own (default)': 'Agent 不會自行領取此任務（預設）', 'Add subtask... (Enter to add)': '新增子任務…（按 Enter 加入）', 'Links': '連結', 'Use link type': '使用連結類型', 'Report': '報告', 'for long-form planning or investigation docs stored in Reports.': '適用於存放在「報告」中的長篇規劃或調查文件。', 'Paste /dashboard/reports/... URL': '貼上 /dashboard/reports/... 網址', 'URL or path': '網址或路徑', 'Title is required': '必須填寫標題', 'Agent Persona is required': '必須選擇 Agent 角色'
};
export function t(key: string, locale: string = DEFAULT_LOCALE): string {
  if (locale !== 'zh-Hant') return key;
  return ui[key] ?? uiTaskExtra[key] ?? navigation[key] ?? key;
}
